### ISSUE TITLE
Unable To Sign Up With New Account

### ISSUE THREAD

**Issue by pashneal** [hexanome-04/splendor#1]
Hello!

It seems that I cannot create a new account, only login! However, since the database has no users, I won't be able to move forward from here. Is there any workaround available to add accounts?

**Comment by sandpipes** [comment]
The default admin account is:
username: maex
password: abc123_ABC123

Other default values for the accounts in the database can be found in setup/LobbyService/ls-db-setup.sql

**Comment by pashneal** [comment]
Amazing, thanks!
