### ISSUE TITLE
server-1 is trying to register itself with the lobby-service-1, but the registration process fails

### ISSUE THREAD

**Issue by BarryTheShen** [hexanome-04/splendor#2]
This is the full logs when it launch. After it launch it just doesn't work. it cannot register as game service:
database-1       | [Entrypoint] MySQL Docker Image 8.0.31-1.2.10-server
database-1       | [Entrypoint] Starting MySQL 8.0.31-1.2.10-server
database-1       | 2024-03-02T08:18:44.365412Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
database-1       | 2024-03-02T08:18:44.367028Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.31) starting as process 1
database-1       | 2024-03-02T08:18:44.377560Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
database-1       | 2024-03-02T08:18:44.588018Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
database-1       | 2024-03-02T08:18:44.813696Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
database-1       | 2024-03-02T08:18:44.813879Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
database-1       | 2024-03-02T08:18:44.847223Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
database-1       | 2024-03-02T08:18:44.847284Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.31'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
lobby-service-1  | Starting up the Lobby Service...
lobby-service-1  | 2024-03-02 08:18:51.229  INFO 1 --- [           main] e.k.l.g.controller.PlatformLauncher      : Starting PlatformLauncher v1.0.0 on 1e5ebd7c463e with PID 1 (/LS/ls.jar started by root in /LS)
lobby-service-1  | 2024-03-02 08:18:51.233  INFO 1 --- [           main] e.k.l.g.controller.PlatformLauncher      : The following profiles are active: prod
lobby-service-1  | 2024-03-02 08:18:52.444  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
lobby-service-1  | 2024-03-02 08:18:52.554  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 90ms. Found 1 repository interfaces.
lobby-service-1  | 2024-03-02 08:18:53.542  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$467afcc7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
lobby-service-1  | 2024-03-02 08:18:53.634  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$df28c501] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
lobby-service-1  | 2024-03-02 08:18:53.648  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
lobby-service-1  | 2024-03-02 08:18:53.654  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@37fb0bed' of type [org.springframework.security.oauth2.provider.expression.OAuth2MethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
lobby-service-1  | 2024-03-02 08:18:53.665  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityConfig' of type [eu.kartoffelquadrat.ls.accountmanager.config.MethodSecurityConfig$$EnhancerBySpringCGLIB$$3a0e8f24] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
lobby-service-1  | 2024-03-02 08:18:53.676  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
lobby-service-1  | 2024-03-02 08:18:54.255  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 34172 (http)
lobby-service-1  | 2024-03-02 08:18:54.304  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
lobby-service-1  | 2024-03-02 08:18:54.306  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.22]
lobby-service-1  | 2024-03-02 08:18:54.435  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
lobby-service-1  | 2024-03-02 08:18:54.436  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3090 ms
lobby-service-1  | 2024-03-02 08:18:55.410  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
lobby-service-1  |      name: default
lobby-service-1  |      ...]
lobby-service-1  | 2024-03-02 08:18:55.526  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.10.Final}
lobby-service-1  | 2024-03-02 08:18:55.528  INFO 1 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
lobby-service-1  | 2024-03-02 08:18:55.766  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
lobby-service-1  | 2024-03-02 08:18:56.182  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
lobby-service-1  | 2024-03-02 08:18:57.242  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
lobby-service-1  | 2024-03-02 08:18:59.125  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: OrRequestMatcher [requestMatchers=[Ant [pattern='/oauth/token'], Ant [pattern='/oauth/token_key'], Ant [pattern='/oauth/check_token']]], [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@4eb166a1, org.springframework.security.web.context.SecurityContextPersistenceFilter@2e09c51, org.springframework.security.web.header.HeaderWriterFilter@14998e21, org.springframework.security.web.authentication.logout.LogoutFilter@310aee0b, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@4b5a078a, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@2f3166a, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@6dd1f638, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@554c4eaa, org.springframework.security.web.session.SessionManagementFilter@596a7f44, org.springframework.security.web.access.ExceptionTranslationFilter@6de6faa6, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@279dd959]
lobby-service-1  | 2024-03-02 08:18:59.154  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration$NotOAuthRequestMatcher@3289079a, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@32fa809f, org.springframework.security.web.context.SecurityContextPersistenceFilter@536d97f8, org.springframework.security.web.header.HeaderWriterFilter@526b2f3e, org.springframework.security.web.authentication.logout.LogoutFilter@28f9fedd, org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter@35ee466f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@3c50ad4b, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@37496720, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@788ba63e, org.springframework.security.web.session.SessionManagementFilter@6f2e1024, org.springframework.security.web.access.ExceptionTranslationFilter@7343922c, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@7593ea79]
lobby-service-1  | 2024-03-02 08:18:59.173  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@5a0bef24, org.springframework.security.web.context.SecurityContextPersistenceFilter@11eed657, org.springframework.security.web.header.HeaderWriterFilter@338b49d3, org.springframework.security.web.authentication.logout.LogoutFilter@a5bbaec, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@708f018e, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@19a31b9d, org.springframework.security.web.session.SessionManagementFilter@2aa7399c, org.springframework.security.web.access.ExceptionTranslationFilter@2be95d31, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@334ebcaa]
lobby-service-1  | 2024-03-02 08:18:59.623  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
lobby-service-1  | 2024-03-02 08:18:59.683  WARN 1 --- [           main] aWebConfiguration$JpaWebMvcConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
lobby-service-1  | 2024-03-02 08:19:00.255  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 34172 (http) with context path ''
lobby-service-1  | 2024-03-02 08:19:00.259  INFO 1 --- [           main] e.k.l.g.controller.PlatformLauncher      : Started PlatformLauncher in 9.864 seconds (JVM running for 10.489)
lobby-service-1  | Lobby Service up and running. Verification echo available at "/api/online".
lobby-service-1  | 2024-03-02 08:19:05.186  INFO 1 --- [io-34172-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
lobby-service-1  | 2024-03-02 08:19:05.187  INFO 1 --- [io-34172-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
lobby-service-1  | 2024-03-02 08:19:05.201  INFO 1 --- [io-34172-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 14 ms
lobby-service-1  | 2024-03-02 08:19:05.385  INFO 1 --- [io-34172-exec-1] o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
server-1         | 
server-1         |   .   ____          _            __ _ _
server-1         |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
server-1         | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
server-1         |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
server-1         |   '  |____| .__|_| |_|_| |_\__, | / / / /
server-1         |  =========|_|==============|___/=/_/_/_/
server-1         |  :: Spring Boot ::                (v2.7.5)
server-1         | 
server-1         | 2024-03-02 08:19:07.963  INFO 1 --- [           main] c.h.s.SplendorGameApplication            : Starting SplendorGameApplication v1.0 using Java 17.0.5 on 1fc6150e14a8 with PID 1 (/server/splendorGame.jar started by root in /server)
server-1         | 2024-03-02 08:19:07.975  INFO 1 --- [           main] c.h.s.SplendorGameApplication            : The following 1 profile is active: "prod"
server-1         | 2024-03-02 08:19:09.895  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 33402 (http)
server-1         | 2024-03-02 08:19:09.911  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
server-1         | 2024-03-02 08:19:09.912  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.68]
server-1         | 2024-03-02 08:19:10.026  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
server-1         | 2024-03-02 08:19:10.027  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1954 ms
server-1         | 2024-03-02 08:19:10.901  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 33402 (http) with context path ''
server-1         | 2024-03-02 08:19:10.964  INFO 1 --- [           main] c.h.s.SplendorGameApplication            : Started SplendorGameApplication in 3.881 seconds (JVM running for 4.79)
server-1         | 2024-03-02 08:19:10.968  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Checking if game service (Splendor Orient) is already registered.
lobby-service-1  | 2024-03-02 08:19:11.044 ERROR 1 --- [io-34172-exec-4] e.k.l.g.controller.RegistryException     : Can not look up parameters for game service: "splendor_BASE_ORIENT". No such game service is registered.
server-1         | 2024-03-02 08:19:11.067  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Attempting to register our game service (Splendor Orient).
server-1         | 2024-03-02 08:19:11.507  INFO 1 --- [io-33402-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
server-1         | 2024-03-02 08:19:11.508  INFO 1 --- [io-33402-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
server-1         | 2024-03-02 08:19:11.511  INFO 1 --- [io-33402-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
client-1         | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
client-1         | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
client-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
client-1         | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
client-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
client-1         | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
client-1         | /docker-entrypoint.sh: Configuration complete; ready for start up
client-1         | 2024/03/02 08:19:12 [notice] 1#1: using the "epoll" event method
client-1         | 2024/03/02 08:19:12 [notice] 1#1: nginx/1.23.3
client-1         | 2024/03/02 08:19:12 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
client-1         | 2024/03/02 08:19:12 [notice] 1#1: OS: Linux 5.19.0-46-generic
client-1         | 2024/03/02 08:19:12 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
client-1         | 2024/03/02 08:19:12 [notice] 1#1: start worker processes
client-1         | 2024/03/02 08:19:12 [notice] 1#1: start worker process 22
client-1         | 2024/03/02 08:19:12 [notice] 1#1: start worker process 23
lobby-service-1  | 2024-03-02 08:19:13.450  WARN 1 --- [io-34172-exec-5] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidGrantException, Bad credentials
server-1         | 2024-03-02 08:19:13.490  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Checking if game service (Splendor Orient) is already registered.
lobby-service-1  | 2024-03-02 08:19:13.508 ERROR 1 --- [io-34172-exec-6] e.k.l.g.controller.RegistryException     : Can not look up parameters for game service: "splendor_BASE_ORIENT". No such game service is registered.
server-1         | 2024-03-02 08:19:13.515  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Attempting to register our game service (Splendor Orient).
lobby-service-1  | 2024-03-02 08:19:14.310  WARN 1 --- [io-34172-exec-7] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidGrantException, Bad credentials
server-1         | 2024-03-02 08:19:14.316  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Checking if game service (Splendor Orient) is already registered.
lobby-service-1  | 2024-03-02 08:19:14.327 ERROR 1 --- [io-34172-exec-8] e.k.l.g.controller.RegistryException     : Can not look up parameters for game service: "splendor_BASE_ORIENT". No such game service is registered.
server-1         | 2024-03-02 08:19:14.331  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Attempting to register our game service (Splendor Orient).
lobby-service-1  | 2024-03-02 08:19:15.090  WARN 1 --- [io-34172-exec-9] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidGrantException, Bad credentials
server-1         | 2024-03-02 08:19:15.095  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Checking if game service (Splendor Orient) is already registered.
lobby-service-1  | 2024-03-02 08:19:15.102 ERROR 1 --- [o-34172-exec-10] e.k.l.g.controller.RegistryException     : Can not look up parameters for game service: "splendor_BASE_ORIENT". No such game service is registered.
server-1         | 2024-03-02 08:19:15.104  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Attempting to register our game service (Splendor Orient).
lobby-service-1  | 2024-03-02 08:19:15.845  WARN 1 --- [io-34172-exec-1] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidGrantException, Bad credentials
server-1         | 2024-03-02 08:19:15.848  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Checking if game service (Splendor Orient) is already registered.
lobby-service-1  | 2024-03-02 08:19:15.856 ERROR 1 --- [io-34172-exec-2] e.k.l.g.controller.RegistryException     : Can not look up parameters for game service: "splendor_BASE_ORIENT". No such game service is registered.
server-1         | 2024-03-02 08:19:15.861  INFO 1 --- [           main] c.h.splendorgame.control.Initializer     : Attempting to register our game service (Splendor Orient).
lobby-service-1  | 2024-03-02 08:19:16.682  WARN 1 --- [io-34172-exec-3] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidGrantException, Bad credentials
server-1         | 2024-03-02 08:19:16.694 ERROR 1 --- [           main] c.h.splendorgame.control.Initializer     : Failed to register game with lobby service.
server-1         | 2024-03-02 08:19:16.781 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
server-1         | 
server-1         | ca.hexanome04.splendorgame.model.SplendorException: Unable to register game service!
server-1         |      at ca.hexanome04.splendorgame.control.Initializer.registerWithLobbyService(Initializer.java:126) ~[classes!/:1.0]
server-1         |      at ca.hexanome04.splendorgame.control.Initializer.init(Initializer.java:87) ~[classes!/:1.0]
server-1         |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
server-1         |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
server-1         |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
server-1         |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
server-1         |      at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar!/:5.3.23]
server-1         |      at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
server-1         |      at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.5.jar!/:2.7.5]
server-1         |      at ca.hexanome04.splendorgame.SplendorGameApplication.main(SplendorGameApplication.java:28) ~[classes!/:1.0]
server-1         |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
server-1         |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
server-1         |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
server-1         |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
server-1         |      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[splendorGame.jar:1.0]
server-1         |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[splendorGame.jar:1.0]
server-1         |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[splendorGame.jar:1.0]
server-1         |      at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[splendorGame.jar:1.0]
server-1         | 
server-1         | 2024-03-02 08:19:16.837  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
server-1         | 2024-03-02 08:19:16.843  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Destroying Spring FrameworkServlet 'dispatcherServlet'
server-1 exited with code 1

**Comment by sandpipes** [comment]
Did you modify the default database or delete any users?

There's a service account that's required for the game to communicate with the lobby service.
